[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remapping = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

solc = "0.8.29"

[profile.default.fuzz]
runs = 1000
max_test_rejects = 100000
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[profile.default.invariant]
runs = 100
depth = 100
fail_on_revert = true
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[profile.ci]
fuzz_runs = 10000
invariant_runs = 1000

[profile.lite]
fuzz_runs = 50
invariant_runs = 10

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = true
quote_style = "double"
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
